[package]
name = "Mandelplotter1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.55.0"
humantime = "2.1.0"
imgui = "0.11.0"
imgui-opengl-renderer = "0.12.1"
